---
title: "data_filtering"
output: html_document
date: "2025-05-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readxl)   # for reading Excel
library(dplyr)    # for filtering, summarizing, etc.
library(tidyr)    # for reshaping data if needed
```
```{r}
df <- read_excel("data/covid_monthly_domesticviolence.xlsx")

```

```{r}
df <- df %>%
  mutate(n_missing = rowSums(is.na(select(., where(is.numeric)))))

country_missing <- df %>%
  group_by(Country) %>%
  summarise(
    total_rows = n(),
    total_missing = sum(n_missing),
    avg_missing_per_row = mean(n_missing),
    .groups = "drop"
  )

```

```{r}
df_cleaned <- df %>%
  filter(n_missing < 6)

```
```{r}
library(stringr)
pattern <- "CHINA|ARMENIA|MOLDOVA|SLOVENIA|BAHAMAS|UZBEKISTAN"
df_filtered <- df_cleaned %>%
  filter(!str_detect(Country, pattern))


```

```{r}
df_filtered <- df_filtered %>%
  filter(rowSums(select(., where(is.numeric), -n_missing), na.rm = TRUE) >= 35)

```
```{r}
write.csv(df_filtered, "data/filtered_domesticviolence_monthly.csv", row.names = FALSE)

```

